### ISSUE TITLE
ruby 2.0.0 and/or 2.1, rails 4 compatibility?

### ISSUE THREAD

**Issue by mfittko** [jnunemaker/toystore#14]
First of all, I love the gem and would like to continue using it in my projects (yes, I am using toystore in production) because it gives me the ability to create typecasted copies of API model-objects which can also be stored/cached flexibly on a backend of my choice.

Is this repository still maintained? If yes it would be awesome if you could at least add travis testing for ruby 2.0.0 and 2.1. As many already did, I am planning to move on to rails 4.0 on production too, so it would be great if you could at least check for compatibility there as well and update the gemspec if it is given.

If on the other hand the repository won't be maintained any more, perhaps you have an idea which alternatives could be possibly used then.

Thanks!!

**Comment by jnunemaker** [comment]
I didn't know if anyone other than me was using it. I would like to see ruby 2.0 and 2.1 compat, along with rails 4, but I don't have time right now. I'll try to make a note to look at it when I do though.

**Comment by mfittko** [comment]
Great, it's just to make sure that I can keep using toystore in future iterations. I am also using mongoid because I couldn't get the mongo adapter for toystore to run properly; and mongoid is also still on 1.9.3 on it's stable branch, so I can't update at the moment anyway. Unfortunately I can't just make a fork of toystore and add the stuff by myself, because my boss just wants to use official gems. And I am not sure if I wouldn't mess things up when there would be problems with 2.0/2.1 and I would try to fix them :D

Well, now you know that at least someone out there uses toystore and is really happy with it. I did a lot of research and I think it does an awesome job when programming a rails app against an external API.
(The only warning I can give any unexperienced user is that the default memory store adapter shouldn't be used for object caching on a passenger server, because it will lose memory when processes are spawned...)

**Comment by slemiere** [comment]
I would love that as well, some users seems to have already worked on it (https://github.com/smartlogic/toystore/tree/rails4 for instance).

**Comment by mfittko** [comment]
I would also contribute, just don't know where to start, also have limited time and would need proper reviews =) The question is if they will continue with the gem at smartlogic or if it is gonna be a dead end. No idea, if the other repo could be merged back since it is no direct descendant of @jnunemaker's gem.

**Comment by jnunemaker** [comment]
Odd that they started from newtoy instead of my fork (since I created it for newtoy and carried it on after).
