### ISSUE TITLE
Rails 3.2 compatibility?

### ISSUE THREAD

**Issue by mateomurphy** [jnunemaker/toystore#7]
Any specific reason why the gemspec reads:
      activemodel (~> 3.0, < 3.2)
      activesupport (~> 3.0, < 3.2)
?

**Comment by jnunemaker** [comment]
A few incompatibilities. Haven't had time to see how to fix them and make it backwards compatible.

**Comment by chrislloyd** [comment]
:+1:

**Comment by jnunemaker** [comment]
This is fixed.
